### PR TITLE
Degrade ValueError in WELOPEN

### PR DESCRIPTION
**Pull request by berland**
When WELOPEN is attempted applied to non-existing connections,
skip these instead of erroring hard. Eclipse seems to just warn
in those cases

### CODE REVIEW

**Comment by tklov11** [comment]
The problem is that ecl2df do not recognize that welopen is applied to a predefined list of wells.

**Review by wouterjdb — APPROVED** [review]
LGTM 👍

**Comment by berland** [comment]
> The problem is that ecl2df do not recognize that welopen is applied to a predefined list of wells.

That problem is now covered by #218

**Comment by berland** [comment]
Ok, based on #218 we should maybe hold this merge until it is confirmed that Eclipse actually will ignore WELOPEN on non-existing i,j,k.

**Review by tklov11 — APPROVED** [review]
Looks good to me.

**Comment by berland** [comment]
Closing. Ecl2df should error hard when it thinks the output is wrong.

**Pull request closed without merging**
