### PR TITLE
Fix erroneous PVTG support in ecl2df.pvt

### PR DESCRIPTION
**Pull request by berland**
Apparently forgotten initially. Mistake was uncovered through adding test code warranted by codecov.io

### CODE REVIEW

**Review by eivindsm — COMMENTED** [review]
Looks like export of DENSITY is no longer supported; is it supported by another function in ecl2df ?

**Comment by berland** [comment]
> Looks like export of DENSITY is no longer supported; is it supported by another function in ecl2df ?

It's still there in `df2ecl_density`, but `df2ecl_pvtg` will no longer erroneously dump density data..

**Comment by berland** [comment]
> Looks like export of DENSITY is no longer supported; is it supported by another function in ecl2df ?

It's still there in `df2ecl_density`, but `df2ecl_pvtg` will no longer erroneously dump density data..

**Review by eivindsm — APPROVED** [review]
Perfect!

**Pull request merged**
