### PR TITLE
Update pre-commit configuration

### PR DESCRIPTION
**Pull request by berland**

### CODE REVIEW

**Comment by anders-kiaer** [comment]
+0 -0? Easy to review :slightly_smiling_face:

**Comment by asnyv** [comment]
> +0 -0? Easy to review 🙂

Sure he shouldn't add an entry in the changelog @anders-kiaer? 😉

**Comment by asnyv** [comment]
It actually seems like the first commit has changes though 🤔

**Comment by asnyv** [comment]
They were already included in https://github.com/equinor/ecl2df/pull/350

**Comment by berland** [comment]
> They were already included in #350

ah!

**Pull request closed without merging**
